### ISSUE TITLE
Type filter is broken in v0.2.0

### ISSUE THREAD

**Issue by lzakharov** [g4s8/envdoc#13]
Got error when using the latest version [v0.2.0](https://github.com/g4s8/envdoc/releases/tag/v0.2.0). Everything works fine with `v0.1.2`. Minimal example to reproduce problem:

```go
package main

import "time"

//go:generate go run github.com/g4s8/envdoc@v0.2.0 -output environments.md -type Config

type Config struct {
	// Some time.
	SomeTime MyTime `env:"SOME_TIME"`
}

type MyTime time.Time

func (t *MyTime) UnmarshalText(text []byte) error {
	tt, err := time.Parse("2006-01-02", string(text))
	*t = MyTime(tt)
	return err
}
```

```sh
➜  go generate ./...
panic: expected type node root child, got 4

goroutine 1 [running]:
main.(*inspector).traverseAST(0x14000125b78, 0x14000126f80, {0x16ee330f2, 0x6})
        /Users/lz/go/pkg/mod/github.com/g4s8/envdoc@v0.2.0/inspector.go:59 +0x344
main.(*inspector).inspectFile(0x14000125b78, {0x1400000e0c7, 0x7})
        /Users/lz/go/pkg/mod/github.com/g4s8/envdoc@v0.2.0/inspector.go:51 +0x2e0
main.(*generator).generate(0x1400007d040, {0x1011bc838, 0x14000050a70})
        /Users/lz/go/pkg/mod/github.com/g4s8/envdoc@v0.2.0/generator.go:99 +0x94
main.run(0x14000125e58)
        /Users/lz/go/pkg/mod/github.com/g4s8/envdoc@v0.2.0/main.go:133 +0x514
main.main()
        /Users/lz/go/pkg/mod/github.com/g4s8/envdoc@v0.2.0/main.go:70 +0xf0
exit status 2
main.go:5: running "go": exit status 1
```

**Comment by g4s8** [comment]
Sorry about that. I'm going to fix it this week.

**Comment by g4s8** [comment]
It should be fixed in https://github.com/g4s8/envdoc/releases/tag/v0.2.1

**Comment by lzakharov** [comment]
Thanks for your work, appreciate it! Unfortunately, now I see another problem:

```go
package main

import "time"

//go:generate go run github.com/g4s8/envdoc@v0.2.1 -output environments.md
type Config struct {
	// Start date.
	Start Date `env:"START,notEmpty"`
}

// Date is a time.Time wrapper that uses the time.DateOnly layout.
type Date struct {
	time.Time
}

func (t *Date) UnmarshalText(text []byte) error {
	tt, err := time.Parse(time.DateOnly, string(text))
	*t = Date{tt}
	return err
}
```

Generated output:

```md
# Environment Variables

## Config

 - Date is a time.Time wrapper that uses the time.DateOnly layout.

```

**Comment by g4s8** [comment]
> Thanks for your work, appreciate it! Unfortunately, now I see another problem:
> 
> ```go
> package main
> 
> import "time"
> 
> //go:generate go run github.com/g4s8/envdoc@v0.2.1 -output environments.md
> type Config struct {
> 	// Start date.
> 	Start Date `env:"START,notEmpty"`
> }
> 
> // Date is a time.Time wrapper that uses the time.DateOnly layout.
> type Date struct {
> 	time.Time
> }
> 
> func (t *Date) UnmarshalText(text []byte) error {
> 	tt, err := time.Parse(time.DateOnly, string(text))
> 	*t = Date{tt}
> 	return err
> }
> ```
> 
> Generated output:
> 
> ```
> # Environment Variables
> 
> ## Config
> 
>  - Date is a time.Time wrapper that uses the time.DateOnly layout.
> ```
> 
> Expected (`v0.1.2`):
> 
> ```
> # Environment Variables
> 
> ## Config
> 
>  - `START` (**required**, non-empty) - Start date.
> ```

This fix will be included into the next release.

**Comment by g4s8** [comment]
@lzakharov you can try [v0.2.2](https://github.com/g4s8/envdoc/releases/tag/v0.2.2) version now

**Comment by lzakharov** [comment]
Now everything works as expected, thank you.
