### ISSUE TITLE
--all flag causes panic if functions are present in the file

### ISSUE THREAD

**Issue by schleicherse** [g4s8/envdoc#21]
Hi again, 
using the newest version 0.2.3 with the fix  #19 now correctly generates documentation for a unexported struct, thank you for that!

However, I liked it so much that I decided to split my huge struct into 3 smaller ones to have a nice grouping in the generated markdown.

I included the --all flag. This works perfectly, as long as there are **no** **functions** present in the file. When there are functions, it stops with the error:
`panic: expected type node root child, got nodeField ()`

To reproduce:

```go
package main

//go:generate envdoc -output test.md --all
type aconfig struct {
	// this is some value
	somevalue string `env:"SOME_VALUE" envDefault:"somevalue"`
}

type anotherconfig struct {
	// this is some value
	somevalue string `env:"SOME_VALUE" envDefault:"somevalue"`
}

// // when this function is present, go generate panics with "expected type node root child, got nodeField ()".
// func someFuncThatTakesInput(configs ...interface{}) {
// 	// this is some comment
// }

// // When this function is present, go generate will panic with "expected type node root child,got nodeField (int)"
// func someFuncThatReturnsSomething() int {
// 	return 1
// }

// // This function can be present and go generate work fine
// func someUselessFunc() {
// 	// this is some comment
// }
``` 

Without knowing too much about the code of envdoc (or go in general ;) ), I think that traverses everything in the file, looking for types. And because in the two first functions, type definitions are present in the functions signature, it leads to an error somewhere. When a function does not have a type inside the signature, it works fine.

go version 1.22.2
envdoc 0.2.3

**Comment by g4s8** [comment]
Thanks for reporting! Should be fixed in [v0.2.4](https://github.com/g4s8/envdoc/releases/tag/v0.2.4) by #22
