### ISSUE TITLE
-types='*' is not working, -all is

### ISSUE THREAD

**Issue by itsab11** [g4s8/envdoc#26]
version used: 1.0.0
go version 1.22.6

```go
//go:generate envdoc --output environment.md -all
type Appconfig struct {
	// Environment, has some effects on logging. Options are: production, debug, development
	Environment string `env:"ENVIRONMENT" envDefault:"production"`
	// timeout in seconds for DB operations like select or insert
	Timeout_DB int `env:"TIMEOUT_DB" envDefault:"10"`
}

// DBconfig contains all env values needed for configuration of the database connection
type DBconfig struct {
	// Username of Metadatastore Service-Account
	DB_User string `env:"DB_USER,notEmpty"`
	// Password of Metadatastore Service-Account
	DB_Pass string `env:"DB_PASS,notEmpty"`
}
``` 
in a situation like this, the new flag -types='*' results in an empty file, while -all is working, despite the warning.

**Comment by g4s8** [comment]
@itsab11 could you add please `-debug` flag to envdoc args and put the output here?
```
//go:generate envdoc -debug --output environment.md -all
```

**Comment by g4s8** [comment]
could you please add the beginning of the logs (or full log), i suppose there could be issue with `*` escaping, need to see the config parsing logs

**Comment by g4s8** [comment]
This should be fixed (most probably) by unescaping glob patterns, where you use `'*'` or `"*"` args. Please try [v1.0.1](https://github.com/g4s8/envdoc/releases/tag/v1.0.1) release

**Comment by schleicherse** [comment]
sorry for the late answer. I just tried the new version, now it works! 
thank you so much for your effort.

Time to generate some docs :)
