### ISSUE TITLE
Support .env format

### ISSUE THREAD

**Issue by miniscruff** [g4s8/envdoc#8]
Hello, I am wondering if it would be possible to support the `.env` ( https://www.dotenv.org/docs ) format by generating "example" files. I built this sort of thing already here https://github.com/miniscruff/envexample but I think your project has a lot more going on then mine.

I could probably give it a try myself in a PR if you agree.

**Comment by g4s8** [comment]
Hi, looks like a good idea! I think this feature could be implemented with `-format dotenv -output .env.example` CLI args and additional render template in https://github.com/g4s8/envdoc/tree/master/templ

Feel free to submit a PR for this or if you want I can take care of it by myself
